title: Shoichi Koyama))))
author: Shoichi Koyama
avatar: /profile.png
skin: original
subscribe: false
math: true

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-paginate

#paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: sh01
  card: summary
logo: profile.png
social:
  name: Shoichi Koyama
  links:
    - https://twitter.com/sh01
    - https://github.com/sh01k
    - https://www.linkedin.com/in/shoichi-koyama-91972424
    - https://www.researchgate.net/profile/Shoichi-Koyama-2
#google_site_verification: 
lang: en
